/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_ROM_32X4_ROM (
    input [4:0] A,
    input sel,
    output reg [3:0] D
);
    reg [3:0] my_rom [0:19];

    always @ (*) begin
        if (~sel)
            D = 4'hz;
        else if (A > 5'h13)
            D = 4'h0;
        else
            D = my_rom[A];
    end

    initial begin
        my_rom[0] = 4'h8;
        my_rom[1] = 4'h8;
        my_rom[2] = 4'hc;
        my_rom[3] = 4'h8;
        my_rom[4] = 4'ha;
        my_rom[5] = 4'h8;
        my_rom[6] = 4'hc;
        my_rom[7] = 4'h8;
        my_rom[8] = 4'h8;
        my_rom[9] = 4'he;
        my_rom[10] = 4'hc;
        my_rom[11] = 4'h0;
        my_rom[12] = 4'h8;
        my_rom[13] = 4'h8;
        my_rom[14] = 4'hc;
        my_rom[15] = 4'h1;
        my_rom[16] = 4'h8;
        my_rom[17] = 4'he;
        my_rom[18] = 4'hc;
        my_rom[19] = 4'h8;
    end
endmodule

module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module circuit (
  input x_1,
  input x_0,
  input CK,
  output z
);
  wire [4:0] s0;
  wire [3:0] s1;
  wire y_0;
  wire y_1;
  wire y_2;
  wire s2;
  wire s3;
  wire s4;
  assign s0[0] = x_1;
  assign s0[1] = x_0;
  assign s0[2] = y_0;
  assign s0[3] = y_1;
  assign s0[4] = y_2;
  // ROM
  DIG_ROM_32X4_ROM DIG_ROM_32X4_ROM_i0 (
    .A( s0 ),
    .sel( 1'b1 ),
    .D( s1 )
  );
  assign s2 = s1[0];
  assign s4 = s1[1];
  assign s3 = s1[2];
  assign z = s1[3];
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( s2 ),
    .C( CK ),
    .Q( y_2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( s3 ),
    .C( CK ),
    .Q( y_0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( s4 ),
    .C( CK ),
    .Q( y_1 )
  );
endmodule
