-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    A: in std_logic;
    B: in std_logic;
    C: in std_logic;
    D: in std_logic;
    S: out std_logic;
    Y1: out std_logic;
    Y2: out std_logic;
    Y3: out std_logic);
end main;

architecture Behavioral of main is
begin
  Y3 <= NOT A;
  S <= NOT (A AND B AND C AND D);
  Y1 <= NOT (A AND B AND C);
  Y2 <= NOT (A AND B);
end Behavioral;
