/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module circuit (
  input A,
  input B,
  input C,
  input D,
  output S,
  output Y1,
  output Y2,
  output Y3
);
  assign Y3 = ~ A;
  assign S = ~ (A & B & C & D);
  assign Y1 = ~ (A & B & C);
  assign Y2 = ~ (A & B);
endmodule
